import re

sample_pieces = [
    "Józef Michał Poniatowski – Pierre de Médicis (wykonanie koncertowe)",
    "Jerzy Matuszkiewicz – Alternatywy 4 /arr. Tomasz Stolarczyk/",
    "Denis Armitage – Let's all Take it Easy",
    "H. Warren – Chattanoga /arr. Piotr Rybicki/",
    "\u2060Wave Jobim /arr. Philip Thrift/",
    "Joshua fit the Battle \\arr. Jean-Francois Michel/",
    "Denis Armitage – Sweet and Mellow",
    "Ulrich Nehls – Slicky Slide Swing",
    "John Philip Sousa – \u2060The Liberty Bell",
    "Henry Mancini – Pink Panther",
    "\u2060Denis Armitage – Happy-Go-Lucky Rag",
    "O when the saints /arr. Jean-Francois Michel/",
    "J. Williams/Doyle – Harry Potter – Marsz /arr. T. Stolarczyk/",
    "Carson Parks – Something Stupid /arr. T. Stolarczyk/",
    "John Philip Sousa – Washington Post",
    "Ari Barroso – Brazil",
    "Gioachino Rossini - Otello (ver. Rome 1820), wykonanie koncertowe",
    "Gioachino Rossini - Kopciuszek",
    "tłumaczenie libretta: Dorota Sawka",
    "Geoffrey Keating – Dance Hall Suite",
    "Arthur Gray – The Nereids",
    "Jesse Greer – Flapperette",
    "Alan Rudout – Pigs for 4 bassoons",
    "Siergiej Prokofiew – Humoristisches Scherzo",
    "W. Raymuond Walker – The Funny Bunny Hug",
    "Nacio Herb Brown – The Wedding of the Painted Doll",
    "Manuel Panella – El Gato Montes",
    "Nino Rota – Dolce Vita e Amarcord",
    "Nino Rota – Canzone Arrabbiata",
    "The Beatles – She loves you",
    "Chanson Repollsif – French Song",
    "Gioachino Rossini - Kopciuszek",
    "tłumaczenie libretta: Dorota Sawka",
    "Paweł Mykietyn - 3 for 13",
    "Wolfgang Amadeus Mozart - XXII Koncert fortepianowy Es-dur KV 482",
    "Henryk Czyż - Divertimento B-dur Meine Kleine Haydn Musik (1947/77)",
    "Wolfgang Amadeus Mozart - XXIV Koncert fortepianowy c-moll KV 491",
    "Michał Lorenc – Pogoń i Taniec Eleny z filmu Bandyta",
    "Dymitr Szostakowicz – Walc nr 2 z II Suity na orkiestrę jazzową",
    "Waldemar Kazanecki – Temat z filmu Czarne chmury",
    "Andrzej Kurylewicz – Temat z filmu Polskie drogi",
    "Jerzy Matuszkiewicz – Temat z serialu Janosik",
    "Tan Dun – Eternal Vow",
    "Ramin Djawadi – Gra o tron",
    "Andrew Lloyd Webber – Upiór w operze",
    "Ennio Morricone – Obój Gabriela z filmu Misja",
    "Dick Dale – Misirlou z filmu Pulp Fiction",
    "Trevor Jones – Promentory z filmu Ostatni Mohikanin",
    "Hans Zimmer – Piraci z Karaibów",
    "Aranżacje: Cellostrada",
    "Frederick Loewe – temat z musicalu My fair Lady",
    "Glenn Miller – Moon Light Serenade",
    "John Kander – New York, New York",
    "Henry Mancini – Moon River z filmu Śniadanie u Tiffany’ego",
    "Leonard Bernstein – America z musicalu West Side Story",
    "George Gershwin – Sumertime z musicalu Porgy and Bess",
    "Carlos Gardel – Por Una Cabeza",
    "Nino Rota – Temat z filmu Romeo i Julia",
    "Andrew Lloyd Webber – Temat z musicalu Upiór w operze",
    "Nino Rota – Temat z filmu Ojciec chrzestny",
    "Wojciech Kilar - Temat z filmu Trędowata",
    "Andrzej Kurylewicz - Temat z serialu Polskie drogi",
    "James Horner - My heart will go on z filmu Titanic",
    "Hans Zimmer - Temat z filmu Piraci z karaibów",
    "FINAŁ 21. FESTIWALU MUZYKI POLSKIEJ",
    "Fryderyk Chopin - Scherzo b-moll (arr. K. Respondek)",
    "Emil Młynarski - I Koncert skrzypcowy d-moll op. 11",
    "Ignacy Jan Paderewski - Symfonia h-moll",
    "Zacznij od Bacha",
    "Nauczmy się żyć obok siebie",
    "Lubię wracać",
    "Opowiadaj mi",
    "Zabiorę Cię dziś na bal",
    "Suita utworów z płyty Zbigniew Wodecki 1976",
    "Cała jesteś w skowronkach",
    "Medytacje wiejskiego listonosza",
    "Prześliczna wiolonczelistka",
    "Wierniejsza od marzenia",
    "Jeszcze Kocham",
    "Wymyśliłem Ciebie",
    "C’est la Vie",
    "Myśmy byli sobie pisani",
    "Jak na lotni",
    "Wieczór nad rzeką zdarzeń",
    ": Błażej Michna",
    "Mischa Spoliansky – Tobie śpiewam tę pieśń, opr. M. Smyda",
    "Imre Kalman – Tak jak gołąbeczki dwa",
    "Fred Raymond – Juliszka z Budapesztu",
    "Henryk Wars – Umówiłem się z nią na dziewiątą, opr. M. Smyda",
    "Robert Stolz – Pokochaj mnie, opr. W. Świderski",
    "Henryk Wars – Nic o tobie nie wiem, opr. M. Smyda",
    "Zygmunt Karasiński – Każdemu wolno kochać",
    "Henryk Wars – Zimny drań, opr. T. Chmiel",
    "Bronisław Kaper – Ninon, opr. W. Świderski",
    "Henryk Wars – Powróćmy jak za dawnych lat",
    "Wolfgang Amadeus Mozart – Marsz turecki, opr. M. Smyda",
    "Jacques Offenbach – Aria ze śmiechem z operetki Perichola",
    "Janusz Stokłosa – Okręt z musicalu Polita, opr. M. Smyda",
    "Imre Kalman – Nie szukaj szczęścia z operetki Księżniczka czardasza",
    "Franz Lehar – Graj Cyganie z operetki Hrabina Marica",
    "Robert Stolz – Śpiewaj, kochaj, opr. W. Świderski",
    "Jacek Wójcicki – Piosenka dla Jana Kiepury",
    "Robert Stolz – Brunetki, blondynki, opr. W. Świderski",
    "Henryk Wars – Na cześć młodości, opr. Mieczysław Smyda",
    "Johann Sebastian Bach – Fuga d-moll",
    "Gabriel Fauré – Berceuse op. 16",
    "Gabriel Fauré – Romans bez słów op.17 nr 3",
    "Antonio Ruiz-Pipó – Canción y Danza nr 1",
    "Edward Grieg – Erotik op. 43 nr 5",
    "Mieczysław Karłowicz – Pieśni:",
    "Zasmuconej",
    "Skąd pierwsze gwiazdy",
    "Na śniegu",
    "Pamiętam ciche, jasne złote dnie",
    "Po szerokim morzu",
    "Idzie na pola",
    "trad. Scarborough Fair",
    "trad. Danny Boy",
    "Alexander Borodin – Tańce połowieckie (fragment)",
    "Claude Debussy – La fille aux cheveux de lin",
    "Astor Piazzolla – Libertango",
    "Astor Piazzolla – Oblivion",
    "Astor Piazzolla – Adiós Nonino",
    "Andrew Lloyd-Webber – All I Ask of You",
    "Jean Sibelius - Valse triste",
    "Aranżacje utworów: Błażej Michna",
    "Mischa Spoliansky – Tobie śpiewam tę pieśń, opr. M. Smyda",
    "Imre Kalman – Tak jak gołąbeczki dwa",
    "Fred Raymond – Juliszka z Budapesztu",
    "Henryk Wars – Umówiłem się z nią na dziewiątą, opr. M. Smyda",
    "Robert Stolz – Pokochaj mnie, opr. W. Świderski",
    "Henryk Wars – Nic o tobie nie wiem, opr. M. Smyda",
    "Zygmunt Karasiński – Każdemu wolno kochać",
    "Henryk Wars – Zimny drań, opr. T. Chmiel",
    "Bronisław Kaper – Ninon, opr. W. Świderski",
    "Henryk Wars – Powróćmy jak za dawnych lat",
    "Wolfgang Amadeus Mozart – Marsz turecki, opr. M. Smyda",
    "Jacques Offenbach – Aria ze śmiechem z operetki Perichola",
    "Janusz Stokłosa – Okręt z musicalu Polita, opr. M. Smyda",
    "Imre Kalman – Nie szukaj szczęścia z operetki Księżniczka czardasza",
    "Franz Lehar – Graj Cyganie z operetki Hrabina Marica",
    "Robert Stolz – Śpiewaj, kochaj, opr. W. Świderski",
    "Jacek Wójcicki – Piosenka dla Jana Kiepury",
    "Robert Stolz – Brunetki, blondynki, opr. W. Świderski",
    "Henryk Wars – Na cześć młodości, opr. Mieczysław Smyda",
    "Johann Strauss II – Nad pięknym modrym Dunajem",
    "Johann Strauss II – Aria Adeli Taki pan jak pan z operetki Zemsta nietoperza",
    "Johann Strauss II – Annen-Polka op. 117",
    "Johannes Brahms – Taniec węgierski nr 5",
    "Imre Kálmán – Czardasz Silvy z operetki Księżniczka Czardasza",
    "Vittorio Monti – Czardasz",
    "Franz Lehár – Kiedy skrzypki grają z operetki Cygańska miłość",
    "Johann Strauss II – Pizzicato Polka op. 449",
    "E. Valentin – Polka Janosz",
    "Imre Kálmán – Czardasz Gdy cygańska piosnka płacze z operki Hrabina Marica",
    "Josef Strauss – Feuerfest op. 269",
    "Johannes Brahms – Taniec węgierski nr 7",
    "Franz Lehár – Kto me usta całuje ten śni z operetki Giuditta",
    "Johann Strauss II – Trisch-Trasch Polka op. 214",
    "Stanisław Moniuszko – Polna różyczka",
    "Stanisław Moniuszko – Krakowiak",
    "Stanisław Moniuszko – Groźna dziewczyna",
    "Stanisław Moniuszko – Kapral",
    "Stanisław Moniuszko – Polonez z opery Hrabina",
    "Stanisław Moniuszko – Pieśń wieczorna",
    "Stanisław Moniuszko – recytatyw i aria Halki z II aktu opery Halka",
    "Stanisław Moniuszko – recytatyw i dumka Jadwigi Biegnie słuchać w lasy, knieje z opery Straszny dwór",
    "Stanisław Moniuszko – Aria Miecznika Kto z mych dziewek z opery Straszny dwór",
    "Pieśni w aranżacji Błażeja Michny",
    "Roman Statkowski - I Kwartet smyczkowy F-dur cz. II i IV",
    "Stanisław Moniuszko - I Kwartet smyczkowy d-moll cz. II i cz. IV (A la krakowiak)",
    "Piosenki Kabaretu Starszych Panów i Henryka Warsa",
    "Antonio Vivaldi - Le Quattro Stagioni | 4 Pory roku",
    "Krzysztof Penderecki - Agnus Dei",
    "Leonard Bernstein - Serenade after Plato's „Symposium\" na skrzypce solo, smyczki, harfę i perkusję",
    "Ralph Vaughan Williams - Fantazja na temat Thomasa Tallisa",
    "Dmitrij Szostakowicz - Symfonia kameralna c-moll op. 110a",
    "Edith Piaf:",
    "Padam padam",
    "La vie en rose (muzyka: Louis Guglielmi)",
    "Sous le ciel de Paris",
    "Milord (tekst: Georges Moustaki, muzyka: Marguerite Monnot)",
    "Mon Dieu (tekst: Michel Vaucaire, muzyka: Charles Dumont)",
    "Charles Aznavour:",
    "Les deux guitares (tekst: Charles Aznavour, muzyka: Ivan Vassiliev)",
    "La boheme (tekst: Jacques Plante, muzyka: Charles Aznavour)",
    "Juliette Gréco:",
    "Parlez-moi d'amour (tekst: Jean Lenoir, muzyka: Jean Lenoir)",
    "La vie s'evite",
    "Non monsieur, je n'ai pas vingt ans",
    "Accordeon",
    "Serge Gainsbourg – La javanaise (tekst: Serge Gainsbourg, muzyka: Serge Gainsbourg)",
    "Serge Lama – Je suis malade (tekst: Serge Lama, muzyka: Alice Dona)",
    "Yves Montand – Les feuilles (tekst: Jacques Prévert, muzyka: Joseph Kosma)",
    "Léo Ferré – Avec le temps (tekst i muzyka: Léo Ferré)",
    "Utwory Fryderyka Chopina",
    "Claude Debussy – Sonata na flet, altówkę i harfę",
    "Maurice Ravel - Sonatina en trio fis-moll (opr. Carlos Salzedo)",
    "Maciej Negrey – Ścieżki w ogrodzie",
    "André Jolivet – Petit suite",
    "dr hab. Konrad Wnęk, prof. UJ - wykład pt. Dźwięki ciszy. Straty muzyki polskiej w czasie II wojny światowej 1939-1945",
    "Władysław Żeleński - Konrad Wallenrod",
    "Fryderyk Chopin:",
    "Ballada As-dur op. 47",
    "Etiuda gis-moll op. 25 nr 5",
    "Nokturn G-dur op. 37 nr 2",
    "Walc Es-dur Op. 18",
    "Andante spianato i Wielki Polonez Es-dur op. 22",
    "Ballada f-moll op. 52",
    "Sonata b-moll op. 35",
    "Wariacje op. 2 na temat La ci darem la mano",
    "Wolfgang Amadeus Mozart – Symfonia nr 41 C-dur KV 551 Jowiszowa",
    "Karol Szymanowski – III Symfonia Pieśń o nocy op. 27",
    "Wolfgang Amadeus Mozart – Symfonia nr 41 C-dur KV 551 Jowiszowa",
    "Karol Szymanowski – III Symfonia Pieśń o nocy op. 27",
    "Bella Italia – Muzyka włoska przez wieki",
    "Karol Szymanowski – Etiuda b-moll (arr. G. Fitelberg)",
    "Karol Szymanowski – I Koncert skrzypcowy op. 35",
    "Aleksandr Skriabin – III Symfonia c-moll op. 43 Boski poemat",
    "Karol Szymanowski – Etiuda b-moll (arr. G. Fitelberg)",
    "Karol Szymanowski – I Koncert skrzypcowy op. 35",
    "Aleksandr Skriabin – III Symfonia c-moll op. 43 Boski poemat",
    "Joseph Haydn – Stworzenie świata",
    "Joseph Haydn – Stworzenie świata",
    "W programie m.in.",
    "Ludwig van Beethoven – IX Symfonia d-moll op. 125",
    "W programie m.in.",
    "Ludwig van Beethoven – IX Symfonia d-moll op. 125",
    "Johann Sebastian Bach:",
    "– Schafe können sicher weiden BWV 208",
    "– Jesus bleibet meine Freude BWV 147",
    "Juliusz Stattler – Duo pour deux pianos op. 27",
    "Michał Świerzyński – 5 Petits Morceaux pour deux pianos",
    "Eliza Markowska – Romance Symphonique",
    "Henryk Pachulski – Polonez op. 5",
    "Astor Piazzolla:",
    "– Milonga del Ángel",
    "– Adiós Nonino",
    "– Libertango",
    "Szczepan Tesarowicz – Quasi una partita",
    "Johann Sebastian Bach – III Partita E-dur BWV 1006 w wersji F. Davida z 1843 roku, wydana jako VI Sonata E-dur",
    "Wojciech Widłak – Po jesieni",
    "Johann Sebastian Bach – V Suita wiolonczelowa c-moll BWV 1011 w skrzypcowej wersji F. Davida z około 1865 roku, wydana jako V Suita g-moll",
    "Ludwig van Beethoven – Trio B-dur Arcyksiążęce op. 97",
    "Aaron Alter – Solar Rays",
    "Robert Schumann – Trio fortepianowe nr 1 d-moll op. 63",
    "Mieczysław Karłowicz:",
    "– Mów do mnie jeszcze op. 3 nr 1",
    "– Nie płacz nade mną op. 3 nr 7",
    "– Smutną jest dusza moja op. 1 nr 6",
    "Eugeniusz Morawski:",
    "– Un grand sommeil noir",
    "– Las płaczących brzóz",
    "– Die Mitternacht",
    "Richard Strauss:",
    "– Zueignung op. 10 nr 1",
    "– Sonata Es-dur op. 18",
    "– Ruhe, meine Seele! op. 27 nr 1",
    "– Cäcilie op. 27 nr 2",
    "– Heimliche Aufforderung op. 27 nr 3",
    "– Morgen! op. 27 nr 4",
    "Ludwig van Beethoven – Sonata F-dur op. 5 nr 1",
    "Robert Schumann – Fünf Stücke im Volkston op. 102",
    "Witold Lutosławski – Grave. Metamorphoses",
    "Robert Schumann – Märchenbilder op. 113",
    "Robert Schumann – Adagio i Allegro op. 70",
]


def extract_composer(piece):
    composer_pattern = re.compile(
        r"^([A-Z][a-zA-ZàáâäãåąćčćęèéêëėįìíîïłńñòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÑÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ\s\.\-\/]+?)(?:\s*[–\-]\s+|\s+[–\-]|:)"
    )
    composer_match = composer_pattern.match(piece)
    if composer_match:
        return composer_match.group(1).strip()
    else:
        None


for piece in sample_pieces:
    composer = extract_composer(piece)
    if not composer:
        print(f"Piece: {piece}")
        print(f"Composer: idk\n")
    else:
        print(f"Piece: {piece}")
        print(f"Composer: {composer}\n")
